kumuluzee:
  name: loaderAgent
  env:
    name: dev
  version: 1.0.1 # ${git.build.version}
  server:
    #base-url: http://localhost:8001
    http:
      port: 8003
  dev:
    scan-libraries:
      - marketplace-common
  openapi-mp:
    enabled: true
    ui:
      enabled: true
    server-auto-config:
      enabled: false
      original-uri-check: false
  grpc:
#    server:
#      http:
#        port: 8083
    clients:
      - name: catalog
        port: 8081
        address: localhost
#        certFile: /path/to/cert/file
#        keyFile: /path/to/key/file
#        chainFile: /path/to/chain/file

  health:
    logs:
      enabled: true
      type: readiness
      level: FINE
      period-s: 60
    checks:
      disk-space-health-check:
        threshold: 10000
  metrics:
    servlet:
      enabled: true
    web-instrumentation:
      - name: metricsEndpoint
        url-pattern: /metrics/*
